cmake_minimum_required(VERSION 3.10)

function(third_parties)
    file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/thirdparty)
    math(EXPR steps "${ARGC}-1")
    foreach(N RANGE 1 ${steps})
        include("build_${ARGV${N}}")
        set(DIR ${PROJECT_BINARY_DIR}/thirdparty/${ARGV${N}})
        message(STATUS "preparing ${ARGV${N}}")
        if (NOT EXISTS ${DIR})
            prepare(${DIR})
        endif()
        build(${DIR})
        set_paths(${DIR} ${ARGV0})
        message(STATUS "${ARGV${N}} ready")
    endforeach()
endfunction()
